### ISSUE TITLE
Does not build with serde=1.0.225

### ISSUE THREAD

**Issue by artiga033** [loro-dev/loro#810]
[serde 1.0.225](https://crates.io/crates/serde/1.0.225), has just release, and with that version loro does not build.

At the time when this issue was created, just `cargo new` a new project and then `cargo add loro && cargo build` could reproduce this.

<details>
<summary>build log</summary>

```
cargo build
    Updating crates.io index
     Locking 166 packages to latest Rust 1.89.0 compatible versions
   Compiling serde_json v1.0.145
   Compiling loro-common v1.6.0
   Compiling loro-kv-store v1.6.0
   Compiling loro-internal v1.6.1
error[E0433]: failed to resolve: could not find `__private` in `serde`
   --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/encoding/arena.rs:445:1
    |
445 | #[columnar(vec, ser, de, iterable)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
    |
    = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/encoding/outdated_encode_reordered.rs:1584:1
     |
1584 | #[columnar(ser, de)]
     | ^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
     |
     = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/state/tree_state.rs:1627:5
     |
1627 |     #[columnar(ser, de)]
     |     ^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
     |
     = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `__private` in `serde`
   --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/encoding/arena.rs:445:1
    |
445 | #[columnar(vec, ser, de, iterable)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
    |
    = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
    |
1   + use std::option::Option;
    |

error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/encoding/outdated_encode_reordered.rs:1584:1
     |
1584 | #[columnar(ser, de)]
     | ^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
     |
     = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
     |
1    + use std::option::Option;
     |

error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> /home/artiga/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/loro-internal-1.6.1/src/state/tree_state.rs:1627:5
     |
1627 |     #[columnar(ser, de)]
     |     ^^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
     |
     = note: this error originates in the attribute macro `columnar` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
     |
1587 +     use std::option::Option;
     |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `loro-internal` (lib) due to 10 previous errors
```
</details>

[Cargo.lock.tar.gz](https://github.com/user-attachments/files/22374490/Cargo.lock.tar.gz)

As a workaround, it builds if specify:
```
[dependencies]
loro = "1.6.1"
serde = "=1.0.224"
```
